### ISSUE TITLE
Better fix for enormous unitMagnitude overflowing in bucket calculations

### ISSUE THREAD

**Issue by marshallpierce** [jonhoo/hdrsample#14]
Port https://github.com/HdrHistogram/HdrHistogram/pull/118.

**Comment by jonhoo** [comment]
I'm guessing we can deal with this too now that that PR got merged.

**Comment by marshallpierce** [comment]
Yup, in progress.

**Comment by marshallpierce** [comment]
Ignore #118, port the new hotness instead: https://github.com/HdrHistogram/HdrHistogram/pull/120

**Comment by marshallpierce** [comment]
Landed in #16
