### ISSUE TITLE
Criterion data in repo

### ISSUE THREAD

**Issue by marshallpierce** [jonhoo/hdrsample#19]
Is it right that `.criterion` is checked in? It seems like it's using that as a baseline to compare against or something, which isn't applicable on my hardware. Also, presumably if you were benchmarking against a baseline, wouldn't you want to set the baseline on a particular revision, then apply the changes under consideration?

**Comment by jonhoo** [comment]
Yeah, Criterion is *supposed* to do regression testing whenever you run it, and it uses `.criterion` for this. And they advice that you should check it in. However, given how broken it currently is, plus the fact that it doesn't take into account running on different machines, I think we can just delete it.

**Comment by jonhoo** [comment]
Closed by #23.
