### ISSUE TITLE
Add method for clamped recording

### ISSUE THREAD

**Issue by jonhoo** [jonhoo/hdrsample#72]
In some benchmarking scenarios, I am running into extreme outliers, often due to a bug in the system or due to hitting a scaling wall. When these happen, my benchmark binary crashes, since I record using something like:
```rust
let us = elapsed.as_secs() * 1_000_000 + elapsed.subsec_nanos() as u64 / 1_000;
hist.record(us).unwrap();
```
Operations generally take ~10µs, but the outliers can easily grow to tens of *seconds*. So even with liberal bounds, the record will fail. When I hit these outliers, I don't actually care about *how* much of an outlier they are, since I don't expect any "regular" samples beyond, say, ~1ms. In this case, what I really want is the ability to record values clamped to the range of the histogram (which should then never fail). I end up writing code like:
```rust
if hist.record(us).is_err() {
   let m = hist.high();
    hist.record(m).unwrap();
}
```
It'd be really nice if I could instead write:
```rust
hist.record_clamped(us);
```

@marshallpierce thoughts?

**Comment by marshallpierce** [comment]
That makes a lot of sense. My holiday OSS todo is already growing but I'll see if I can explore this a bit and come up with a strawman. :)

**Comment by marshallpierce** [comment]
Perhaps we should use `saturating` to echo `saturating_add()`? (We already use saturated counts under the hood, so maybe that's confusing... or maybe that's enough of a buried implementation detail that we could re-use the terminology.)

**Comment by jonhoo** [comment]
No, I think `saturating_add` is a good name for it. This one I'll probably have time to code up, especially because I want it in my current project :p Just wanted your input for whether this is a sensible thing to do.

**Comment by marshallpierce** [comment]
Yeah, I think it's reasonable. I don't want to force consumers into not-really-error-handling for a common case, and I definitely want to encourage not consuming memory needlessly if you really only care about 1, 2, 3, disastrous for your buckets.
